databases:
  - name: bughunter-db
    databaseName: bughunter
    user: bughunter

services:
  - type: web
    name: bughunter
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bughunter_site.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bughunter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4